### PR TITLE
fix: fix a bug in hello world line

### LINKED ISSUE #1: BUG: found bug in main.py in hello world
There was an error printing hello world

### PR DESCRIPTION
**Pull request by mjcortejo**
hello,

this will fix a bug in hello world line

### CODE REVIEW

**Review by ChadElRicardo — COMMENTED** [review]
This looks nice

**Comment by mjcortejo** [comment]
@ChadElRicardo tnx boi

**Comment by ejcbernal** [comment]
Very nice indeed

**Comment by mjcortejo** [comment]
@ejcbernal TNX BOI

**Pull request merged**
